### ISSUE TITLE
V4 push?

### ISSUE THREAD

**Issue by gorillica** [giocomai/omeka-s-docker#2]
Hi, I see you’ve updated your Dockerfile to download Omeka 4.0, but so far there’s no release on GitHub or Docker Hub to push this through. Would you be able to push the release?

**Comment by giocomai** [comment]
If you check on Docker Hub - https://hub.docker.com/r/giocomai/omeka-s-docker/tags - you'll see that there are the appropriate tags as expected. 

[v4.0.0](https://hub.docker.com/layers/giocomai/omeka-s-docker/v4.0.0/images/sha256-3a44256a122829446a216e47b0c3011a525a83c6b82824f480402f9d19606a32?context=explore)
[v4.0.0.production](https://hub.docker.com/layers/giocomai/omeka-s-docker/v4.0.0.production/images/sha256-3a44256a122829446a216e47b0c3011a525a83c6b82824f480402f9d19606a32?context=explore)
[v4.0.0.development](https://hub.docker.com/layers/giocomai/omeka-s-docker/v4.0.0.development/images/sha256-c88d8b123afe532f4626ce68b257e00de97ca5c2c46a3e345a7f2e05722817bb?context=explore)

I'm still keeping 3.2.3 for the tagged version for the time being, as upgrading should be a fully conscious choice due to incompatibilities, so I'll wait at least a few more months. 

Dockerfile for 3.2.3 is still available in a separate branch here, and the images will be still be occasionally updated for Docker Hub.

**Comment by gorillica** [comment]
Thanks, Giorgio. I'm feeling embarrassed that I didn't scroll down to see the v4 tags on Docker Hub now!

**Comment by giocomai** [comment]
No worries!
